package com.example.neu.springbootapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

@DynamoDBTable(tableName = "CSYE6225DynamoDB")
public class OneTimeToken {

    @DynamoDBHashKey(attributeName = "Token")
    @DynamoDBAutoGeneratedKey
    private String token;

    @DynamoDBRangeKey(attributeName = "Email")
    private String email;

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
