package com.example.neu.springbootapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

@DynamoDBTable(tableName = "OneTimeTokenTable")
public class OneTimeToken {


    @DynamoDBRangeKey(attributeName = "Token")
    @DynamoDBAutoGeneratedKey
    private String token;

    @DynamoDBHashKey(attributeName = "Email")
    private String email;

    @DynamoDBRangeKey(attributeName = "Expiry")
    private long Expiry;

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public long getExpiry() {
        return Expiry;
    }

    public void setExpiry(long expiry) {
        Expiry = expiry;
    }

    @Override
    public String toString() {
        return "OneTimeToken{" +
                "token='" + token + '\'' +
                ", email='" + email + '\'' +
                ", Expiry=" + Expiry +
                '}';
    }
}
