name: Packer Validator
on:
# For mannually triggering workflow runs
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  # Test's job
  packersyntaxcheck:
    name: validation of packer
    # Runs on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      # checkout against code
      - name: repository checkout
        uses: actions/checkout@v2

      - name: template validation
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          working_directory: packer
          target: ami.pkr.hcl

      - name: check format
        run: ls -la && cd packer && packer fmt --check ami.pkr.hcl





    